### ISSUE TITLE
'make compare' broken on macOS, due to reliance on md5sum

### ISSUE THREAD

**Issue by BenHetherington** [pret/pokered#183] opened 2018-06-06 21:48 UTC
This issue is going to be very much as-per pret/pokecrystal#364…

The `compare` target in the Makefile currently depends on `md5sum`, a command line tool that is included in Linux. However, macOS instead includes the BSD `md5` tool, and as such, when trying to compare the hashes, we're instead informed: `md5sum: No such file or directory`.

To fix this, @PikalaxALT added a tool in pret/pokecrystal@c372aae to do the MD5 calculations, to avoid this dependency on `md5sum`. Would it be possible to add a similar tool to pokered, to fix the same issue?

**Comment by yenatch** [comment] 2018-06-06 22:26
Seems to be a duplicate of this commit. https://github.com/pret/pokecrystal/commit/f03b898250597680f115cec5cec06953b403acf9

md5.c is only used for building graphics. There's no need to include it in pokered. pokecrystal checks if `shasum` exists, and uses `sha1sum` otherwise. https://github.com/pret/pokecrystal/pull/371/commits/f12e42ab6d41740a6e9302f1f12250a0f72c3f9d The same could be done for `md5sum` and `md5`. It doesn't really matter which but sha1 would probably be better.

**Comment by guilt** [comment] 2019-04-15 05:05
The other option is to use `openssl md5` (or any other hash of your choice)

**Closed** 2020-07-05 23:58 UTC
