### ISSUE TITLE
Error compiling wram.asm with rgbasm v0.3.2-20-g4877e6d

### ISSUE THREAD

**Issue by linkmauve** [pret/pokered#163] opened 2017-08-04 15:52 UTC
Even after applying the patch in #147, building fails with:
```
ERROR: wram.asm(3143):
        Constant mustn't be negative: -2
```

**Comment by dannye** [comment] 2017-08-04 22:49
Yeah... That's because declaring negative space is no longer allowed. We used to declare the stack with negative space too, but that got changed.

`
wWaterRate:: db ; d8a4
wWaterMons:: db ; d8a5

	ds wWaterRate - @

wEnemyMons:: ; d8a4
`

The problem is that `wWaterRate` and `wEnemyMons` are at the same address, and there's no easy way declare `wWaterMons` as the byte after `wEnemyMons` since `wEnemyMons` uses the `party_struct` macro.
Using `ds wWaterRate - @` (which evaluates to -2) was the best solution.

**Comment by yenatch** [comment] 2017-08-05 03:18
0.3.2 added unions (rednex/rgbds#193) to solve this problem:
```asm
UNION

wWaterRate:: db ; d8a4
wWaterMons:: db ; d8a5

NEXTU

wEnemyMons:: ; d8a4
wEnemyMon1:: party_struct wEnemyMon1
wEnemyMon2:: party_struct wEnemyMon2
wEnemyMon3:: party_struct wEnemyMon3
wEnemyMon4:: party_struct wEnemyMon4
wEnemyMon5:: party_struct wEnemyMon5
wEnemyMon6:: party_struct wEnemyMon6

wEnemyMonOT::    ds NAME_LENGTH * PARTY_LENGTH ; d9ac
wEnemyMonNicks:: ds NAME_LENGTH * PARTY_LENGTH ; d9ee

ENDU
```

**Comment by yenatch** [comment] 2017-09-28 23:30
This would be fixed by #147. Until then, you could merge it locally or use rgbds 0.2.5.

**Comment by yenatch** [comment] 2017-09-28 23:35
The `- @` cases would need to be replaced with unions to work with rgbds 0.3.3. You can see how this was done in pokecrystal here: https://github.com/pret/pokecrystal/pull/389/commits/63bc19e33d4a26f71e953089c25065094ddd4cc7

Until then, rgbds 0.2.5 will still work.

**Comment by Pokechu22** [comment] 2017-09-28 23:36
Pokémon Red doesn't have printer support, so I assume you're using Yellow.  For that you want pret/pokeyellow#27 (which does both a linkerscript and unions) (though I'll add that I made that PR and I'm not 100% confident with the changes since I really don't know what I'm doing)

**Closed** 2017-09-30 02:41 UTC
