### ISSUE TITLE
One more thing for Linux User

### ISSUE THREAD

**Issue by HOCHAN-LEE** [pret/pokered#228] opened 2019-11-16 10:35 UTC
Hello Sir i love your game i really enjoy pokemon 
thank you for making this game i really appericiate.
there is one problem while installing in linux system, one error occurs 
if you put the "sudo apt-get install make git gcc"
 **'Could not get lock /var/lib/dpkg/lock - open (11 Resource temporarily unavailable)' Errors** this error occurs so i solved this problem by following 
here so please check my issue and upload for the user who have same problem.

(https://www.linuxuprising.com/2018/07/how-to-fix-could-not-get-lock.html)

**Comment by mid-kid** [comment] 2019-11-16 12:38
This issue occurs only when you don't shut down your machine properly or force closing package management programs like the updater.
This isn't the place to explain uncommon package management issues (such as recovering from broken installs, fixing broken dependencies, and this) that have nothing to do with this project. Please refer to the relevant distribution's documentation for that.

**Closed** 2019-11-18 01:20 UTC

**Comment by HOCHAN-LEE** [comment] 2019-11-18 10:52
> This issue occurs only when you don't shut down your machine properly or force closing package management programs like the updater.
thank you for respond i got it.
> This isn't the place to explain uncommon package management issues (such as recovering from broken installs, fixing broken dependencies, and this) that have nothing to do with this project. Please refer to the relevant distribution's documentation for that.
i apologize for making unsuitable issue.. for me my second language is English and i really don't no much about github.. it's just a month ago i started using github so sir where should i tell this kind of problem for other people where is the place i should've posted? 
could you please tell me where it is? 
i will really appreciate it thank you again for your respond ^0^

**Comment by mid-kid** [comment] 2019-11-18 11:16
If you're looking for where to ask these questions, considering the issue is with your linux distribution, which I'm guessing to be either Debian or Ubuntu, you could've asked in any of the forums or Q&A sites about them, such as:
- https://unix.stackexchange.com/
- https://askubuntu.com/
- http://forums.debian.net/
- https://ubuntuforums.org/
- https://www.linuxquestions.org/questions/debian-26/ or https://www.linuxquestions.org/questions/ubuntu-63/
- Relevant IRC channels or bug trackers

If you're looking for where to write the solution, you could report it to your distribution's bug tracker if it's missing from the documentation, or write about it on another site or blog about the subject, just like the link you sent does, which people will be able to find through an internet search.

Thanks for taking the time to help other users through similar problems, but I think this issue is already explained in a lot of places.

**Comment by HOCHAN-LEE** [comment] 2019-11-20 04:39
Thank you so much again, now i know how to contribute about this kind of problem 
and also those sites are really helpful for me.
have a nice day and i hope your project thrive forever!!
