### ISSUE TITLE
How do I assemble on mac?

### ISSUE THREAD

**Issue by testtest765** [pret/pokered#175] opened 2018-02-24 03:53 UTC
I'm on mac. I'm completely new to programming. How do I assemble a ROM that reflects the changes I've made? The command in install.md builds the original disassembly.

**Comment by PikalaxALT** [comment] 2018-02-24 03:54
Run `make` in the directory with the modified code.

**Comment by testtest765** [comment] 2018-02-24 04:02
I'm sorry to be an absolute knob. I'm a little lost. 

Is this what you're referring to?

![image](https://user-images.githubusercontent.com/36781705/36625426-57b0e4d2-18ed-11e8-8f33-3045531aac4c.png)

When I open that I get the following:

![image](https://user-images.githubusercontent.com/36781705/36625441-7e77c536-18ed-11e8-819f-bdcbd54239f0.png)

**Comment by PikalaxALT** [comment] 2018-02-24 04:05
you should be in `Terminal`, not `Finder`

**Comment by testtest765** [comment] 2018-02-24 04:12
@PikalaxALT I really appreciate you trying to guide me through this. I'm sorry to say that I'm still very lost. 

Can you explain this to me as if I'm five years old?

I'm in Finder only because the repository is saved on my desktop.

I'm not sure exactly what to type into the Terminal.

**Comment by PikalaxALT** [comment] 2018-02-24 13:54
cd ~/pokecrystal
    make

**Comment by testtest765** [comment] 2018-02-24 15:36
Thanks!

I tried making a fresh pokered diassembly without any modifications  The only problem is I get the following error:

![image](https://user-images.githubusercontent.com/36781705/36631990-7be54288-194e-11e8-8870-396a1b925a95.png)

**Comment by Asday** [comment] 2018-02-24 16:19
https://github.com/pret/pokered/blob/master/INSTALL.md#mac

**Comment by xCrystal** [comment] 2018-02-24 16:23
Make sure you have the lattest version of rgbds installed (v0.3.5) as of now. Also make sure that you install 32-bit or 64-bit cygwin and rgbds according to your SO.

**Comment by testtest765** [comment] 2018-02-24 17:31
@Asday I've tried that and can successfully build a ROM that way. However, I can't seem to build a ROM from files saved on my mac. 

@xCrystal I have the latest version of rgbds installed. I don't think I can install cygwin since I'm on a mac.

![image](https://user-images.githubusercontent.com/36781705/36633167-99536cea-195e-11e8-880b-0af158e4d9a6.png)

**Comment by PikalaxALT** [comment] 2018-02-24 17:32
git submodule init
    git submodule update

**Comment by testtest765** [comment] 2018-02-24 17:37
@PikalaxALT 
![image](https://user-images.githubusercontent.com/36781705/36633219-82241a5a-195f-11e8-94df-6d2f9c0f2ffd.png)

**Comment by yenatch** [comment] 2018-02-24 17:45
the issue is that `git clone --recursive` also clones the `extras` submodule which has some of the tools needed to build. when you download a zip or leave out `--recursive` the submodule doesn't get cloned. this is why it says they're missing

the simplest way to get the submodule working is to make your folder a git repo. do this:
```
git init
git remote add origin https://github.com/pret/pokered
git fetch origin
git reset --hard origin/master
git submodule update --init
```

this should be fixed by #168, which will not need the submodule to build

**Comment by xCrystal** [comment] 2018-02-24 18:12
@testtest765 My bad, went on autopilot with that reply lol

**Comment by testtest765** [comment] 2018-02-25 19:09
@yenatch  @xCrystal @PikalaxALT

Thank you for all of your help! I've figured it out.

**Comment by yenatch** [comment] 2018-02-25 19:13
oops. i meant `--soft`, not `--hard`

**Closed** 2018-04-23 12:47 UTC
