### ISSUE TITLE
Many important wiki tutorials still not present

### ISSUE THREAD

**Issue by InternetGoblin** [pret/pokered#317] opened 2021-04-04 15:49 UTC
I myself have little to no background in coding; so, I have been heavily reliant on using the various tutorials I've found on the wiki: As well as receiving help through the Pret Discord server. For someone like me, the lack of tutorials on the Pokered and Pokeyellow wiki's hasn't been ideal, especially when they are compared to something like Pokecrystal for example. Several tutorials just don't exist for things that I would assume quite a few people other then me would be interested in implementing. These include:

- New Pokemon (This one especially)
- New Trainer Class
- New HMs/TMs
- New Move effects
- New Party Menu icons
- Full sized back sprites (Another big one)
- Gender for Pokemon
- Infinite use TMs

And many other smaller things that I either cannot remember or I never even thought of. I am well aware a very similar post was made here by the person behind Polished Crystal about a year ago, but many of those tutorials just haven't been made. Hopefully at least a handful of these, especially the new Pokemon and fixed back sprites, tutorials get added soon.

**Comment by Rangi42** [comment] 2021-04-04 15:59
Duplicate of #278.

**Closed by Rangi42** 2021-04-04 15:59 UTC

**Comment by InternetGoblin** [comment] 2021-04-04 16:03
> 
> 
> Duplicate of #278.

Well yeah, but most of that has still not been resolved in over a year
